[feature/order] 주문등록 확인 및 enum 수정
Lotte-Feelmycode/the-parabole-mono-be pull request #125
Opened 2022-10-13 10:13 UTC by chd830

## 개요
주문/결제 FE에서 연결

## 작업한 내용
List로 RequestBody를 받을 수 없어서 Dto로 변환하는 작업 진행 및 FE에서 BE로 주문/결제를 진행했을 때 DB에 값이 업데이트 되는 것 확인
KAKAO_PAY로 저장되고, 주문 상품이 임의로 되어있습니다.

## 앞으로 추가 예정 내용
enum에서 state, value를 가져오는 부분을 stream을 사용하여 변경할 예정

## 이슈번호
[#113]

2022-10-13 10:58 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/controller/OrderInfoController.java
> +    public ResponseEntity<ParaboleResponse> createOrderInfo(@RequestParam Long userId, @RequestBody OrderInfoListDto orderInfoDto) {
api 사용하는 입장에서 body로만 동작하는게 더 좋을거 같아요... dto 안으로 넣어주세요

2022-10-13 10:58 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/dto/OrderInfoDto.java
> +public class OrderInfoDto implements Serializable {
serializable은 없어도 될거 같아요~

2022-10-13 10:58 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/service/OrderInfoService.java
> +    private static final Long DELIVERY_FEE = 3000L;
우리 컨셉을 생각해봤을때 
여러 오픈마켓(판매자)에서 파는거라고 생각하면 마켓마다 배달비가 생기니까 무료로 통일해버리는게 좋을 거 같아요
<img width="557" alt="image" src="https://user-images.githubusercontent.com/52902010/195579000-3fce9321-c87e-405b-9c9a-6018776ba6d3.png">

2022-10-13 10:58 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/service/OrderInfoService.java
> +        OrderInfo orderInfo = new OrderInfo(order, "KAKAO_PAY", orderInfoDto.getProductId(), orderInfoDto.getProductName(), orderInfoDto.getProductCnt(), orderInfoDto.getProductPrice());
```suggestion
        OrderInfo orderInfo = new OrderInfo(
            order, 
            "KAKAO_PAY", 
            orderInfoDto.getProductId(), 
            orderInfoDto.getProductName(), 
            orderInfoDto.getProductCnt(), 
            orderInfoDto.getProductPrice()
        );
```

2022-10-14 00:16 UTC, chd830 commented on src/main/java/com/feelmycode/parabole/controller/OrderInfoController.java
> +    public ResponseEntity<ParaboleResponse> createOrderInfo(@RequestParam Long userId, @RequestBody OrderInfoListDto orderInfoDto) {
넣었습니당

2022-10-14 00:16 UTC, chd830 commented on src/main/java/com/feelmycode/parabole/dto/OrderInfoDto.java
> +public class OrderInfoDto implements Serializable {
삭제완료

2022-10-14 00:18 UTC, chd830 commented on src/main/java/com/feelmycode/parabole/service/OrderInfoService.java
> +    private static final Long DELIVERY_FEE = 3000L;
무료배송으로 변경했습니다. 바꾸는 김에 private static final이랑 private final 사이도 한 칸 띄워서 정리했습니당

2022-10-14 00:25 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/service/OrderInfoService.java
> +import com.feelmycode.parabole.dto.OrderInfoSimpleDto;
line 61 에 대해 comment 달아요 !
TODO: 부분은 CouponService 에서 필요한 로직 같아요
제가 만들게요

2022-10-14 00:57 UTC, chd830 commented on src/main/java/com/feelmycode/parabole/service/OrderInfoService.java
> +import com.feelmycode.parabole.dto.OrderInfoSimpleDto;
넹 확인이용

2022-10-14 01:01 UTC, daeunchung submitted a review, later dismissed

2022-10-14 02:07 UTC, jungeu1509 approved these changes

2022-10-14 02:07 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/controller/OrderController.java
> +
수정할 필요는 없지만 이것도 장바구니에서 계산해서 보내주고 order에서는 스냅샷으로 받아서 저장하는게 맞는거 같아요

<img width="1472" alt="image" src="https://user-images.githubusercontent.com/52902010/195745397-124229d8-dcc9-4aaf-8afd-96ae7d9316c5.png">

2022-10-14 02:07 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/dto/OrderInfoDto.java
> +public class OrderInfoDto implements Serializable {
안지워 졌는데요...?

2022-10-14 02:18 UTC, chd830 commented on src/main/java/com/feelmycode/parabole/dto/OrderInfoDto.java
> +public class OrderInfoDto implements Serializable {
커밋이 안되었나봅니다... 얼른다시 수정해서 올릴게용

2022-10-14 02:58 UTC, chd830 commented on src/main/java/com/feelmycode/parabole/controller/OrderController.java
> +
나중에 필요한 한번에 다 날릴게용 👌🏼

2022-10-14 02:59 UTC, choihyeongjun reviewed
화이팅!!

2022-10-14 02:59 UTC, choihyeongjun commented on src/main/java/com/feelmycode/parabole/service/OrderInfoService.java
> +                                            orderInfoDto.getProductPrice());
띄어쓰기 정렬해주세용

2022-10-14 03:22 UTC, choihyeongjun submitted a review, later dismissed
LGTM

2022-10-14 03:37 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/domain/OrderInfo.java
> +    private Integer payState;
도메인에서는 enumtype 을 가져야한다고 생각해요

2022-10-14 08:19 UTC, chd830 commented on src/main/java/com/feelmycode/parabole/domain/OrderInfo.java
> +    private Integer payState;
수정햇습니다

2022-10-17 00:45 UTC, jungeu1509 requested changes
OrderInfo에서 에러가 나네요
set함수에서 Integer 로 받고있는데 OrderState 에다 넣으려고 하니 에러가 나고있습니다.

Integer로 받은걸 OrderState 형식의 enum으로 바꿔주세요

2022-10-17 03:50 UTC, chd830 commented on src/main/java/com/feelmycode/parabole/domain/OrderInfo.java
> +    private Integer payState;
수정정하겠습니다 저거 수정하면 손댈부분이 많아서 Integer로 처리해두고 차후에 수정하겠습니다.

2022-10-17 03:50 UTC, chd830 commented
> OrderInfo에서 에러가 나네요 set함수에서 Integer 로 받고있는데 OrderState 에다 넣으려고 하니 에러가 나고있습니다.
> 
> Integer로 받은걸 OrderState 형식의 enum으로 바꿔주세요

수정완료했습니다.

2022-10-17 06:01 UTC, IMHYEWON approved these changes
LGTM👍

2022-10-17 06:06 UTC, jungeu1509 approved these changes
LGTM

2022-10-17 06:06 UTC, merged