[feature/login] 일반로그인과 소셜로그인 구현
Lotte-Feelmycode/the-parabole-mono-be pull request #160
Opened 2022-10-26 01:40 UTC by daeunchung

## 개요
LTNS 간만의 PR ~

## 작업한 내용
로그인과 소셜 로그인 구현했습니다

## 리뷰 가이드
jwt 토큰이 잘 받아와 지는지, 
로그인한 유저의 주문, 상품, 쿠폰이 불러와지는지
로그인과 로그아웃 동작여부 (+ 상황별 토큰 유무)

# 공지
1. google 소셜 로그인이 추가되어서 client id와 client secret을 submodule에 추가 해놓았습니다.
한번씩 update 해주세요

2. mono-be 의 api 창구에서 받는 input 매개변수가 수정되어야합니다 . 
즉 controller 함수가 수정되어야 한다는 뜻입니다. 
각자 자신이 맡은 be api 가 로그인이 필요한 부분인지,
로그인 하지 않아도 (인증없이) 외부인에게 제공해주어야 하는 서비스인지 판단하고 api를 수정해주시길 바랍니다.
ex ) 메인 상품목록, 이벤트 목록  : 누구나 접근 가능
but 주문 조회, 이벤트 등록 : 로그인 필요

## 테스트 결과
![image](https://user-images.githubusercontent.com/46639550/197912462-6b90f17c-bfa1-41a1-97ca-4ce8a46dcb9c.png)
![image](https://user-images.githubusercontent.com/46639550/197912487-8d15b0c4-2585-4461-b9e3-c8e3eb7faaef.png)
![image](https://user-images.githubusercontent.com/46639550/197912515-ada07681-4d68-42a0-8eeb-52872e9511a6.png)

## 할말
be PR merge 되어야 동작 확인 가능합니다.

## 이슈번호
#159 #148

2022-10-26 02:14 UTC, chd830 commented on src/main/java/com/feelmycode/parabole/security/ApplicationOAuth2User.java
> +}
```suggestion
}

```

2022-10-26 02:27 UTC, chd830 commented on src/main/java/com/feelmycode/parabole/repository/CouponRepository.java
>      List<Coupon> findAllByNameAndSellerId(String couponName, Long sellerId);
```suggestion
    List<Coupon> findAllValidBySellerId(Long sellerId);
    List<Coupon> findAllByNameAndSellerId(String couponName, Long sellerId);
```

2022-10-26 02:27 UTC, chd830 commented on src/main/java/com/feelmycode/parabole/security/JwtAuthenticationFilter.java
> +                log.info("Authenticated user ID : " + userId );
치환문자 사용해주세용
```suggestion
                log.info("Authenticated user ID : {}", userId );
```

2022-10-26 02:27 UTC, chd830 commented on src/main/java/com/feelmycode/parabole/security/OAuthUserServiceImpl.java
> +        final String googleEmail = (String) oAuth2User.getAttributes().get("email");
지금은 그냥 진행하더라도 카카오나 다른 소셜 로그인에서 이 코드를 재사용하게 된다면 네이밍을 변경해주세요.

2022-10-26 02:27 UTC, chd830 commented on src/main/java/com/feelmycode/parabole/security/RedirectUrlCookieFilter.java
> +                logger.error("Could not set user authentication in security context", ex);
얘는 어디서 나오는 logger죠?

2022-10-26 02:27 UTC, chd830 commented on src/main/java/com/feelmycode/parabole/security/TokenProvider.java
> +    private static final String SECRET_KEY = "NMA8JPctFuna59f5NMA8JPctFuna59f5NMA8JPctFuna59f5";
SECRET_KEY는 yml에서 가지고 있는 쪽이 보안상으로 좋을 거 같아요

2022-10-26 02:42 UTC, IMHYEWON reviewed
고생했어용~

2022-10-26 02:42 UTC, IMHYEWON commented on src/main/java/com/feelmycode/parabole/dto/UserDto.java
> +// NOTICE: 혜원언니가 사용중인 dto같아서 수정하지 않고 인증용 UserDTO 를 만들어서 작업했습니다.
제가 작성한 생성자는 두고 이 dto를 사용하셔도 될거같아요~

2022-10-26 02:42 UTC, IMHYEWON commented on src/main/java/com/feelmycode/parabole/global/config/WebSecurityConfig.java
> +//            .antMatchers("/","/api/v1", "/api/v1/auth/**", "/oauth2/**", "/api/v1/coupon/list/**").permitAll()
필요없는 주석은 지워주세용 ㅎㅎ

2022-10-26 02:42 UTC, IMHYEWON commented on src/main/java/com/feelmycode/parabole/global/config/WebSecurityConfig.java
> +            .antMatchers("/","/api/v1/auth/**").permitAll()
auth만 풀어두면.. 메인화면 (상품 리스트) 또는 이벤트 화면은 접근하지 못할것같은데요? 로그인안해도 접근할 수 있는 부분이 있어야 하니깐요~

2022-10-26 02:42 UTC, IMHYEWON commented on src/main/java/com/feelmycode/parabole/repository/CouponRepository.java
> +    @Query(value="select c from Coupon c where c.expiresAt <= current_date")
왜 갑자기 쿼리를 썼을까요..?! docs를 먼저 확인 해보는 습관을 가집시당~
[spring data JPA docs](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.repositories)

2022-10-26 02:42 UTC, IMHYEWON commented on src/main/java/com/feelmycode/parabole/repository/UserCouponRepository.java
> +    @Query(value="select uc from UserCoupon uc where uc.coupon.expiresAt <= current_date")
이부분도요~

2022-10-26 02:42 UTC, IMHYEWON commented on src/main/java/com/feelmycode/parabole/security/JwtAuthenticationFilter.java
> +/* 인증 부분만 구현, 유효 시간 검사는 생략 */
유효시간 검사 왜 생략인가용? 다음에 할려면 TODO로 적어주세요

2022-10-26 02:42 UTC, IMHYEWON commented on src/main/java/com/feelmycode/parabole/security/OAuthSuccessHandler.java
> +    private static final String LOCAL_REDIRECT_URL = "http://localhost:3000";
이 부분은 나중에 프론트서버 배포하면 어떻게 처리하나요? 배포서버에서 온 요청인지 개발(로컬)에서 온 요청인지 구분해야하지 않을까요?

2022-10-26 02:44 UTC, daeunchung commented on build.gradle
> +    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.2'
✔️

2022-10-26 05:18 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/controller/AuthController.java
> +    public ResponseEntity<?> registerUser(@RequestBody UserDTO userDTO) {
✔️

2022-10-26 05:19 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/controller/UserController.java
> +//    }
✔️제거완료

2022-10-26 05:20 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/domain/User.java
> +    private String authProvider; // example : facebook
맞아요 ! 여러 소셜로그인 구현하기에 enum으로 처리해서 다음 pr을 열도록 할게용

2022-10-26 05:21 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/global/config/WebMvcConfig.java
> +//        registry.addMapping("/api/v1/**)
✔️

2022-10-26 05:22 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/global/config/WebSecurityConfig.java
> +            .disable()
✔️

2022-10-26 05:22 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/global/config/WebSecurityConfig.java
> +            .and()
✔️

2022-10-26 05:23 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/global/config/WebSecurityConfig.java
> +            .and()
✔️

2022-10-26 05:23 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/security/ApplicationOAuth2User.java
> +}
✔️

2022-10-26 05:24 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/repository/CouponRepository.java
>      List<Coupon> findAllByNameAndSellerId(String couponName, Long sellerId);
✔️

2022-10-26 05:25 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/security/JwtAuthenticationFilter.java
> +                log.info("Authenticated user ID : " + userId );
✔️

2022-10-26 05:25 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/security/OAuthUserServiceImpl.java
> +        final String googleEmail = (String) oAuth2User.getAttributes().get("email");
넵 ~ 변경될거에요 ✔️

2022-10-26 05:26 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/security/RedirectUrlCookieFilter.java
> +                logger.error("Could not set user authentication in security context", ex);
✔️

2022-10-26 05:27 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/global/config/WebSecurityConfig.java
> +//            .antMatchers("/","/api/v1", "/api/v1/auth/**", "/oauth2/**", "/api/v1/coupon/list/**").permitAll()
✔️

2022-10-26 05:30 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/global/config/WebSecurityConfig.java
> +            .antMatchers("/","/api/v1/auth/**").permitAll()
✔️

2022-10-26 05:37 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/security/JwtAuthenticationFilter.java
> +/* 인증 부분만 구현, 유효 시간 검사는 생략 */
✔️

2022-10-26 05:39 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/security/OAuthSuccessHandler.java
> +    private static final String LOCAL_REDIRECT_URL = "http://localhost:3000";
```
let backendHost;

//const hostname = window && window.location && window.location.hostname;
const hostname = 'prod';

if (hostname === 'prod') {
  backendHost = 'http://localhost:8080';
} else if (hostname === 'dev') {
  backendHost = 'http://13.125.163.134';
} else {
  backendHost = 'http://localhost:8080';
}

export const API_BASE_URL = `${backendHost}/api/v1`;
```
다음 pr에서 이런식으로 빼셔 공통 처리해줄게요

2022-10-26 05:39 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/security/OAuthSuccessHandler.java
> +    private static final String LOCAL_REDIRECT_URL = "http://localhost:3000";
✔️

2022-10-26 05:46 UTC, daeunchung commented
@chd830 
모든 파일마다 마지막 줄 line 정리 ✔️ 
모든 파일 주석 제거 ✔️

2022-10-26 05:52 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/repository/UserCouponRepository.java
> +    @Query(value="select uc from UserCoupon uc where uc.coupon.expiresAt <= current_date")
✔️

2022-10-26 05:52 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/repository/CouponRepository.java
> +    @Query(value="select c from Coupon c where c.expiresAt <= current_date")
✔️

2022-10-26 06:10 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/dto/UserDto.java
> +// NOTICE: 혜원언니가 사용중인 dto같아서 수정하지 않고 인증용 UserDTO 를 만들어서 작업했습니다.
✔️

2022-10-26 06:15 UTC, chd830 commented on src/main/java/com/feelmycode/parabole/domain/User.java
> +    private String authProvider; // example : facebook
👌🏼

2022-10-26 10:03 UTC, jungeu1509 approved these changes
소셜로그인으로 회원가입할때 추가 정보를 입력받을지 여부도 궁금합니다
그리고 노션에 작업할때 참고했던 자료랑 어떤부분 참고했는지 문서화 해서 처음부터 작업해도 따라할 수 있도록 부탁드려요

2022-10-27 05:44 UTC, IMHYEWON reviewed
굳~~

2022-10-27 05:44 UTC, IMHYEWON commented on src/main/java/com/feelmycode/parabole/repository/CouponRepository.java
> +    List<Coupon> findAllValidBySellerId(Long sellerId);
이렇게 하면 되지않나용? 그리고 findAllValidBySellerId로 돌려봤는데 seller_id 조회 조건이 안먹는 것 같아요! 조회결과 값 혹시 보셨나요?

2022-10-27 05:50 UTC, jungeu1509 submitted a review, later dismissed

2022-10-27 06:28 UTC, choihyeongjun reviewed
고생했다이 👍

2022-10-27 06:28 UTC, choihyeongjun commented on src/main/java/com/feelmycode/parabole/domain/User.java
> +@AllArgsConstructor
떼 주세용

2022-10-27 06:28 UTC, choihyeongjun commented on src/main/java/com/feelmycode/parabole/domain/User.java
> +//    @GenericGenerator(name="system-uuid", strategy = "uuid")
이거 지워주세요

2022-10-27 06:28 UTC, choihyeongjun commented on src/main/java/com/feelmycode/parabole/security/OAuthSuccessHandler.java
> +//        response.getWriter().write(token);
얘도 지웠나요?

2022-10-27 06:54 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/repository/CouponRepository.java
> +    List<Coupon> findAllValidBySellerId(Long sellerId);
동작되는 함수로 수정완료. 테스트도 했어용

2022-10-27 06:55 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/domain/User.java
> +@AllArgsConstructor
✔️

2022-10-27 06:55 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/domain/User.java
> +//    @GenericGenerator(name="system-uuid", strategy = "uuid")
✔️

2022-10-27 06:56 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/security/OAuthSuccessHandler.java
> +//        response.getWriter().write(token);
✅

2022-10-27 06:58 UTC, daeunchung commented
처음 구현하는 부분이다 보니, PR comment 중에 다른 방식으로 수정해 달라는 요청이 들어올 경우를 대비하려고  사용하지 않는 코드임에 불구하고 못 지우고 주석 처리 한 경향이 있네요. 
발전할게요 감삼당

2022-10-27 07:40 UTC, IMHYEWON submitted a review, later dismissed
LGTM 👍

2022-10-28 05:13 UTC, jungeu1509 approved these changes

2022-10-28 05:13 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/domain/User.java
> +//    @NotNull
주석이 필요한가요??

2022-10-28 05:16 UTC, jungeu1509 requested changes
빌드가 안되고 에러납니다.

2022-10-28 05:21 UTC, jungeu1509 approved these changes
아 서브모듈 문제였네요 빌드 잘 됩니다.

2022-10-28 08:41 UTC, IMHYEWON approved these changes
LGTM 👍

2022-10-28 08:41 UTC, jungeu1509 approved these changes
LGTM

2022-10-28 08:42 UTC, merged