[feature/product] Product Rest Docs 생성
Lotte-Feelmycode/the-parabole-mono-be pull request #169
Opened 2022-10-31 01:59 UTC by chd830

2022-11-01 03:45 UTC, jungeu1509 commented on src/test/java/com/feelmycode/parabole/controller/ProductControllerTest.java
> +
이런거 추가해주세요

```suggestion

        // Then
        Assertions.assertEquals(HttpStatus.OK.value(), resp.statusCode());
```

2022-11-02 08:21 UTC, chd830 commented on src/test/java/com/feelmycode/parabole/controller/ProductControllerTest.java
> +
추가햇습니다 ✔️

2022-11-03 05:15 UTC, IMHYEWON commented on src/test/java/com/feelmycode/parabole/controller/ProductControllerTest.java
> +    }
뭔가 잘못된것같아요! api는 판매자 상품목록인데 파라미터는 상품 아이디고 밑에 같은 api 다른 테스트가 있어용

2022-11-03 05:18 UTC, IMHYEWON commented on src/test/java/com/feelmycode/parabole/controller/ProductControllerTest.java
> +        productRepository.deleteById(productId);
저 좀 혼란스러운데 api 테스트 하고 생성된 상품을 삭제해야되는거 아닌가용..????

2022-11-03 05:30 UTC, jungeu1509 commented on src/docs/asciidoc/snippets/product-list/curl-request.adoc
>  ----
product-list는 수정 하시면 안되는데.... ㅠㅠ...

2022-11-03 05:30 UTC, jungeu1509 commented on src/test/java/com/feelmycode/parabole/controller/ProductControllerTest.java
>              .param("storeName", "")
판매자 1로 넣어주세요! 결과목록이 너무 많이 나와요

2022-11-03 06:11 UTC, jungeu1509 requested changes
판매목록에 sellerid=1 넣어서 다시 테스트 부탁드립니다.

2022-11-03 07:47 UTC, chd830 commented
- [ ] controllerTest에서 sellerId=1
- [ ] product-list 수정되어있는지 체크하기
- [ ] api에서 삭제하는 테스트 위치 조정하기
- [ ] 테스트가 잘못되어있는지 확인하기

2022-11-03 07:49 UTC, jungeu1509 commented
충돌도 해결해주세용

2022-11-03 08:46 UTC, jungeu1509 approved these changes
LGTM

2022-11-04 00:26 UTC, IMHYEWON approved these changes

2022-11-04 00:27 UTC, merged