[feature/event-docs] 이벤트 adoc 수정
Lotte-Feelmycode/the-parabole-mono-be pull request #179
Opened 2022-11-04 07:00 UTC by IMHYEWON

## 개요
Rest Docs 이벤트 adoc 수정

![image](https://user-images.githubusercontent.com/37797830/199911132-97158e7e-f7d4-48bd-b8d6-a1e67842afa7.png)

2022-11-04 08:33 UTC, choihyeongjun submitted a review, later dismissed
LGTM

2022-11-04 08:36 UTC, jungeu1509 requested changes
응모 파트 request json 하나 table하나
response json 하나 test하나 있어야 하는데 뭐가 빠졌네요

2022-11-04 08:36 UTC, jungeu1509 commented on src/docs/asciidoc/event.adoc
> +--- === 이벤트 응모 체크
```suggestion
'''

=== 이벤트 응모 체크
```

2022-11-04 08:56 UTC, chd830 commented on src/docs/asciidoc/event.adoc
> +include::{resource-dir}/eventparticipant/curl-request.adoc[]
이 부분 curl-request를 넣나요?

2022-11-04 10:35 UTC, jungeu1509 requested changes
adoc을 일일이 확인은 힘들고 발견한 것만 댓글 달았어요 확인 부탁드립니다.

2022-11-04 10:35 UTC, jungeu1509 commented on src/docs/asciidoc/event.adoc
> +== 이벤트 등록
다른 파일 보면 2단계로 도메인 설명을 해놔서

== 이벤트

=== 이벤트 등록 

이게 맞을거 같아요

2022-11-04 10:35 UTC, jungeu1509 commented on src/docs/asciidoc/event.adoc
> +--- === 이벤트 응모 체크
--- 는 md 스타일 구분선이고 adoc 스타일 구분선은 ''' 이렇게 써요

그리고 제목이랑 구분선이랑 붙어있으면 동작하지 않습니다.

구분선이 필요하다면 제가 제안한 대로 바꾸시고  구분선이 필요없다면 '''을 지워주세요

2022-11-04 10:46 UTC, IMHYEWON commented on src/docs/asciidoc/event.adoc
> +== 이벤트 등록
![image](https://user-images.githubusercontent.com/37797830/199954653-88303378-dfe8-4241-8cd3-d768419de7c6.png)

이렇게 수정했어요!

2022-11-04 10:55 UTC, jungeu1509 approved these changes
LGTM

2022-11-04 11:43 UTC, jungeu1509 reviewed
하나만 수정해주세요 ㅎㅎ;;

2022-11-04 11:43 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/global/util/DatabaseCleaner.java
> +}
```suggestion
}

```

2022-11-04 11:43 UTC, jungeu1509 commented on src/test/java/com/feelmycode/parabole/controller/EventControllerTest.java
> +    }
오옹 이렇게 사용하면 되는군요! 감사합니당

2022-11-06 09:15 UTC, jungeu1509 commented on src/test/java/com/feelmycode/parabole/controller/EventControllerTest.java
> +    }
동작 안하는거 수정해주세요~

2022-11-07 01:37 UTC, jungeu1509 commented on src/test/java/com/feelmycode/parabole/controller/EventControllerTest.java
> +                    fieldWithPath("endAt").type(JsonFieldType.STRING).description("이벤트 종료 일시"),
일시는 어떤식으로 전송하는지 전송 형태를 작성해주세요

```suggestion
                    fieldWithPath("startAt").type(JsonFieldType.STRING).description("이벤트 시작 일시 (yyyy-MM-dd'T'HH:mm:ss)"),
                    fieldWithPath("endAt").type(JsonFieldType.STRING).description("이벤트 종료 일시 (yyyy-MM-dd'T'HH:mm:ss)"),
```

2022-11-07 01:37 UTC, jungeu1509 commented on src/test/java/com/feelmycode/parabole/controller/EventControllerTest.java
> +                        .description("이벤트 경품 유형"),
유형은 어떤게 있는지 어떤식으로 전송하는지 설명해주세요

아래는 예시고 알맞게 수정해주세요

```suggestion
                    fieldWithPath("eventPrizeCreateRequestDtos.[].type").type(JsonFieldType.STRING)
                        .description("이벤트 경품 유형 (상품: PRODUCT /쿠폰: COUPON )"),
```

2022-11-07 03:43 UTC, chd830 commented
@Pathvariable쓸 때  request parameter가 선언 안되어있는거 같은데 
![image](https://user-images.githubusercontent.com/21255149/200221992-4812a80d-8188-4703-98f9-f49ba469bc1e.png)
이거 참고하시면 될 거 같아요

2022-11-07 03:45 UTC, chd830 approved these changes

2022-11-07 05:20 UTC, jungeu1509 approved these changes
LGTM

2022-11-07 05:20 UTC, merged