Feat: Coupon Api 기능 구현 [#6][#15][#21][#22][#27][#32]
Lotte-Feelmycode/the-parabole-mono-be pull request #33
Opened 2022-09-22 11:56 UTC by daeunchung

## 개요
Feat: Coupon Api 기능 구현

## 작업한 내용
- 쿠폰 등록 셀러
- 쿠폰 목록 유저
- 쿠폰 목록 셀러
- 쿠폰 사용자에게 배정
- 쿠폰 사용(상태 변경)
- 쿠폰 정보 출력
- User Entity 설계
- 쿠폰 UUID 구현

## 리뷰 가이드 
HELP
1. Controller 에서  POST 메서드로 
   @RequestParam 을 보내는건 postman 에서 테스트할 줄 아는데
   @RequestBody Long couponId 와 같이 변수를 보내면 body 로 보내도 400이 떠요

## 테스트 결과
![image](https://user-images.githubusercontent.com/46639550/191739918-8a7cdcb5-af1c-4a90-accf-6a0c82d8ed01.png)
API 6개 전부 테스트 성공

## 앞으로 추가 예정 내용
ResponseEntity 와 에러코드 작성 필요

## 기타 내용

## 이슈번호
[#6][#15][#21][#22][#27][#32]

2022-09-23 01:52 UTC, choihyeongjun reviewed
화이팅

2022-09-23 01:52 UTC, choihyeongjun commented on src/main/java/com/feelmycode/parabole/domain/User.java
> +{
괄호 위로 올려서 일치 시킵시당

2022-09-23 01:52 UTC, choihyeongjun commented on src/main/java/com/feelmycode/parabole/domain/User.java
> +    @NotNull
nullable을 ddl생성 할때 notnull 해줄려고 쓴거면 @notnull 해줘도 그 옵션이 들어가 있으니깐 @notnull만 해주면될듯

2022-09-23 01:52 UTC, choihyeongjun commented on src/main/java/com/feelmycode/parabole/domain/coupons/UserCoupon.java
> +    private Integer useState;                            // 쿠폰 사용안함 0   사용완료 1
이거 enum으로 따로 선언해주면 좋을듯

2022-09-23 01:52 UTC, choihyeongjun commented on src/main/java/com/feelmycode/parabole/dto/CouponAvailianceResponseDto.java
> +    private Integer couponType;         // 쿠폰유형 ( 할인율1  할인금액2 )
얘들도 enum으로 따로 처리해주면 좋을듯

2022-09-23 01:52 UTC, choihyeongjun commented on src/main/java/com/feelmycode/parabole/dto/CouponSellerResponseDto.java
> +
왜 슬프게 name 혼자 떨어져있어?

2022-09-23 01:52 UTC, choihyeongjun commented on src/main/java/com/feelmycode/parabole/repository/CouponRepository.java
> +    Coupon findCouponByCouponId(@Param("couponId") Long couponId);
JpaRepository 상속 받았으면 위에 굳이 쿼리를 또 쓸 필요 없을거 같습니당

2022-09-23 01:52 UTC, choihyeongjun commented on src/main/java/com/feelmycode/parabole/service/CouponService.java
> +    @Transactional
트랜잭션 어노테이션 이거 여기에 꼭 있어야 되는거야?? 나도 확실하게 잘 몰라서 물어보는거

2022-09-23 02:03 UTC, chd830 commented on src/main/java/com/feelmycode/parabole/service/SellerService.java
> +}
```suggestion
    }
    
}
```

2022-09-23 02:03 UTC, chd830 commented on src/main/java/com/feelmycode/parabole/service/CouponService.java
> +
```suggestion

```

2022-09-23 02:03 UTC, chd830 commented on src/main/java/com/feelmycode/parabole/service/CouponService.java
> +    @Transactional(readOnly = true)
@Transactional(readOnly = true)를 클래스 이름위에 붙여놓으면 굳이 다 readonly=true를 선언안하고 readonly=false인 부분만 따로 선언해줘서 간결해질 수 있을거 같아요

2022-09-23 02:03 UTC, chd830 commented on src/main/java/com/feelmycode/parabole/repository/CouponRepository.java
> +
```suggestion

```

2022-09-23 02:24 UTC, jungeu1509 requested changes
User는 거의 구현을 해서 안지워도 될거 같은데 Seller 엔티티(컨트롤러, 서비스, 리파지토리)는 다 지우는게 맞는거 같아요

2022-09-23 02:24 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/controller/CouponController.java
> +    /** Set User to UserCoupon :: 즉 쿠폰을 사용자에게 배부 */
메서드 명이 잘 되어있으면 이런 주석은 필요없어요~ 메서드 네이밍을 더 고민하고 주석을 삭제합시다!

2022-09-23 02:24 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/domain/Seller.java
> +}
파일의 맨 마지막줄은 한줄 띄어주는게 좋아요
```suggestion
}

```

2022-09-23 02:24 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/domain/Seller.java
> +    }
seller는 아직 내용이 없어서 seller 엔티티 없애고 sellerId로만 사용해도 될거같아요
user는 그냥 올립시다.

2022-09-23 02:24 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/domain/coupons/Coupon.java
> +@AllArgsConstructor
권장하지 않는 어노테이션입니다

2022-09-23 02:24 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/domain/coupons/Coupon.java
> +    private String createdAt;
baseEntity에 있는 내용이니까 지워야 될거같아요

2022-09-23 02:24 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/domain/coupons/Coupon.java
> +    private String createdAt;
시간 형식은
가장 기본적인 형식(날짜와 시간)은 아래와 같습니다.
2017-03-16T17:40:00+09:00

iso 8601 다시 확인해주세요

2022-09-23 02:24 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/domain/coupons/Coupon.java
> +    private String createdAt;
String 사용 안하기로 했고 LocalDateTime 으로 바꾸기로 했습니다. 바꾸면 iso 8601이 java에서 자동 적용될겁니다.

2022-09-23 02:24 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/dto/CouponAvailianceResponseDto.java
> +    private Integer couponType;         // 쿠폰유형 ( 할인율1  할인금액2 )
enum 공감합니다

2022-09-23 02:24 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/dto/CouponCreateRequestDto.java
> +@AllArgsConstructor
권장하지 않는 어노테이션입니다.

2022-09-23 02:24 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/dto/CouponCreateResponseDto.java
> +    private String couponName;
권장하지 않는 어노테이션입니다.
그리고 함수명 다음줄은 띄어주는게 좋습니다.
```suggestion
public class CouponCreateResponseDto {

    private String couponName;
```

2022-09-23 02:24 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/global/util/UuidApp.java
> +}
```suggestion
public class UuidApp {

    public static String generator() {
    
        UUID uuid = UUID.randomUUID();
        String uuidStr = uuid.toString();
        return uuidStr;
    }
}

```

2022-09-23 02:24 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/repository/CouponRepository.java
> +
```suggestion

```

2022-09-23 02:24 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/service/CouponService.java
> +    @Transactional
@choihyeongjun 
보통 서비스 메서드 마다에 트렌잭션 어노테이션을 다는데 db에서 자원 점유하고 수정할때 그리고 오류가 중간에 발생할때 되돌려주기위해 사용합니당.

2022-09-23 02:24 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/service/CouponService.java
> +        }
상수를 enum으로 혹은 const 처리하면 읽기도 좋고 유지보수하기에도 좋을것 같아요.
다른사람은 1이 뭔지 2가 뭔지 모르니까요

2022-09-23 02:24 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/service/CouponService.java
> +        // save 를 안쓰는 이유는 아마도 cascadeType을 ALL 로 해주었기 때문에 add 해도 persistence가 refresh 됭서?
주석 오타있어요~

2022-09-23 02:24 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/service/SellerService.java
> +
seller 측은 다 지워주세요

2022-09-23 02:27 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/dto/CouponAvailianceResponseDto.java
> +    private Integer couponType;         // 쿠폰유형 ( 할인율1  할인금액2 )
반영했습니다

2022-09-23 02:40 UTC, IMHYEWON commented on src/main/java/com/feelmycode/parabole/domain/User.java
> +    private String updatedAt;
BaseEntity 를 상속받아서 이 필드를 따로 작성할 필요가 없어보여요~

2022-09-23 02:40 UTC, IMHYEWON commented on src/main/java/com/feelmycode/parabole/domain/coupons/Coupon.java
> +    @ColumnDefault("3")
테스트용으로 작성한 부분은 지우고 올려주세요~

2022-09-23 02:40 UTC, IMHYEWON commented on src/main/java/com/feelmycode/parabole/domain/coupons/Coupon.java
> +    private String details;
컬럼명이 details는 detail List처럼 보일 소지가 있어서 필드,컬럼명 둘다 detail로 바꾸는게 좋을 것 같아요, erd도 수정해주세요

2022-09-23 02:40 UTC, IMHYEWON commented on src/main/java/com/feelmycode/parabole/domain/coupons/UserCoupon.java
> +    private String useDate;
배정일시, 사용일시는 LocalDateTime이 아닌 문자열로 사용하나요?

2022-09-23 02:44 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/repository/CouponRepository.java
> +    Coupon findCouponByCouponId(@Param("couponId") Long couponId);
확인했어요! 제가 Optional 공부 후에 전부 다 바꾸도록 해볼게용

2022-09-23 02:48 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/service/CouponService.java
> +    @Transactional
트랜잭션은 다음과 같은 경우 사용한다.

하나의 작업 or 여러 작업을
하나의 작업 단위로 묶어 Commit or Rollback 처리가 필요할 때
특히, JPA를 사용한다면 단일 작업에 대해서는 @Transactional을 직접 선언할 필요가 없다.

JPA의 구현체를 살펴보면 모든 메서드에 이미 @Transactional이 선언되어 있기 때문에 문제가 발생하면 Rollback 처리해주기 때문이다.

이라네 !

2022-09-23 02:50 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/service/CouponService.java
> +    @Transactional(readOnly = true)
넵 반영했어요!

2022-09-23 03:18 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/controller/CouponController.java
> +    /* 1.OK */
넵 감사합니당

2022-09-23 03:22 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/controller/CouponController.java
> +    /** Set User to UserCoupon :: 즉 쿠폰을 사용자에게 배부 */
진짜 도움 많이 되는 코멘트 남겨주시네요, 감동 😢 반영완!

2022-09-23 03:24 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/controller/CouponController.java
> +}
넵!

2022-09-23 03:28 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/domain/coupons/Coupon.java
> +    @ColumnDefault("3")
넵 반영했어요! 언니 진짜 꼼꼼하다 감탄하고갑니다 😮

2022-09-23 03:29 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/domain/coupons/UserCoupon.java
> +    private String useDate;
오후에 String 을 전부 LocalDateTime 으로 변경하는 작업할게요!

2022-09-23 03:36 UTC, daeunchung commented on src/main/java/com/feelmycode/parabole/service/CouponService.java
> +        }
반영했습니다~

2022-09-23 06:09 UTC, IMHYEWON approved these changes

2022-09-23 06:15 UTC, choihyeongjun approved these changes
고생했엉~

2022-09-23 06:23 UTC, jungeu1509 requested changes
seller 제거해주세요

2022-09-23 06:23 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/global/util/UuidApp.java
> +}
```suggestion
}

```

2022-09-23 06:23 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/service/SellerService.java
> +}
```suggestion
}

```

2022-09-26 01:24 UTC, jungeu1509 approved these changes
LGTM

2022-09-26 01:24 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/domain/Seller.java
> +//}
```suggestion
//}

```

2022-09-26 01:24 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/dto/CouponCreateRequestDto.java
> +        private LocalDateTime expiresAt;
```suggestion
        private LocalDateTime validAt;
        private LocalDateTime expiresAt;
```

2022-09-26 01:24 UTC, jungeu1509 commented on src/main/java/com/feelmycode/parabole/global/util/UuidApp.java
> +}
remind

2022-09-26 01:36 UTC, chd830 commented
ProductController랑 BaseEntity에 생기는 충돌 해결했습니당 😃

2022-09-26 03:01 UTC, merged